heartbeat.monitors:
- type: http
  schedule: '@every 10s'
  urls:
    - https://fatmali@github.io
    - https://google.com

  check.request:
    method: GET
    headers:
        'Content-Type': 'application/json' 
  check.response:
       status: 200

- type: icmp
  id: ping-myhost
  name: My Host Ping
  hosts: ["myhost"]
  schedule: '*/5 * * * * * *'
       

output.elasticsearch:
  hosts: ["docker-elk-elasticsearch:9200"]

setup.kibana:
  host: "docker-elk-kibana:5601"